### PR TITLE
Update Docker-Compose to 1.24.0

### PR DESCRIPTION
**Pull request by rhunwicks**
Update Docker-Compose to 1.24.0 to enable `docker-compose build --parallel`

### CODE REVIEW

**Comment by PiDelport** [comment]
For what it's worth, I made this alternative build that adds the upstream docker-compose 1.24.0 binary to the Docker base image:

https://github.com/PiDelport/docker-compose

**Comment by fergyfresh** [comment]
@pidelport they (docker) already maintain an image like yours. I think it would be worth checking that out. Look at the docker/docker-compose github repo for more info.

**Comment by tmaier** [comment]
The Docker Compose version is also available in this image. See 18.09

**Comment by PiDelport** [comment]
@fergyfresh: I looked at that first, but they don't have a version that uses `docker:git` as the base image.

That's the base image we'd like to use for CI, where the builds use ssh and git along with docker-compose.

**Pull request closed without merging**
