### PR TITLE
Fix rust compiler not found error at old alpine linux

### PR DESCRIPTION
**Pull request by kaito3desuyo**
I apologize for not passing the test due to the following reasons.

1. The alpine linux repository used in the docker:1.13 image did not have a rust compiler
2. docker-compose:1.24.* pip dependency is broken

For number 2, I couldn't find a workaround, so I've removed 18.09 from the version matrix file. 
All other versions have confirmed that the test completes successfully.

### CODE REVIEW

**Comment by tmaier** [comment]
cool workaround!

We could also drop all versions which are not supported by Docker anymore... 

What do you think? Do you know where to find that list?

**Comment by tmaier** [comment]
1.13 is super ancient

**Comment by kaito3desuyo** [comment]
yeah I think so too.

https://www.docker.com/blog/extending-support-cycle-docker-community-edition/
According to this blog post by Docker, Docker CE will be supported for 7 months...  
However, looking at the current release cycle, I think this is too short...

Since the release cycle is becoming irregular, it is difficult to determine the range to erase.  
Personally, before v18.06, two years have passed since the last update, so I think it's okay to delete it.

**Comment by tmaier** [comment]
Yes, can you update your pull request for this change. So we remove all images prior 19.

Please also update `build-dependencies` as it should work now

**Comment by kaito3desuyo** [comment]
Okay, I removed version prior v19 from version matrix file.

**Comment by tmaier** [comment]
Thank you very much!

**Pull request merged**
