### PR TITLE
use APK package for compose

### PR DESCRIPTION
**Pull request by okainov**
Disclaimer: I didn't test it, just updated two lines.

As for Alpine 3.10 there is just an APK package with docker-compose.

See https://wiki.alpinelinux.org/wiki/Docker

### CODE REVIEW

**Comment by tmaier** [comment]
Interesting approach. Does it work for you to ins tall a specific version of the package?

https://pkgs.alpinelinux.org/packages?name=docker-compose&branch=v3.12

**Comment by okainov** [comment]
Yep, it works, but with only single equal sign :)  And also the version names might be different, i.e. it's like `1.25.4-r2` now

image

**Comment by tmaier** [comment]
how many and which old versions are supported by alpine directly? Can we find there only the latest one?

**Comment by okainov** [comment]
No idea tbh

**Comment by tmaier** [comment]
Hi @okainov,

as this would reduce our flexibility of which docker-compose versions to support, I decided not to follow this approach and thus, closing this pull request.

Nevertheless, thanks for the contribution and the idea.

**Pull request closed without merging**
